controller_manager:
  ros__parameters:
    update_rate: 80
    use_sim_time: true


    steering_controller:
      type: velocity_controllers/JointGroupVelocityController

    drive_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

steering_controller:
  ros__parameters:
    joints:
      - steering_joint
#    pid: { p: 10.0, i: 0.01, d: 0.0 }
    publish_rate: 80.0

drive_wheel_controller:
  ros__parameters:
    joints:
      - drive_wheel_joint
#    pid: { p: 10.0, i: 0.01, d: 0.0 }
    publish_rate: 80.0


joint_state_broadcaster:
  ros__parameters:
    publish_rate: 80.0
